### ISSUE TITLE
Paypal button disabled

### ISSUE THREAD

**Issue by SoniaAbed** [appcelerator-modules/ti.paypal#10]
Hi,

I'm trying to send my app to few testers via installr, but when I sign my app with ad hoc provisioning profile the PayPal button is disabled!! when I run directly from Appcelerator studio it is enabled..

**Comment by ashcoding** [comment]
The difference between Appc studio and signing it is that in Android, it's debug vs release. Is there some settings you used that uses this fact?

**Comment by SoniaAbed** [comment]
I fixed the issue thank you 👍
